twist_mux:
  topics:
  - name    : Joystick
    topic   : robot/teleop/cmd_vel
    timeout : 0.5
    priority: 100

  - name    : Navigation
    topic   : robot/move_base/cmd_vel
    timeout : 0.5
    priority: 50

  - name    : External
    topic   : robot/cmd_vel
    timeout : 0.5
    priority: 10

  locks:
  - name    : Software Runstop
    topic   : robot/software_runstop
    timeout : 0.0    
    priority: 150
